import * as assert from 'assert';
import * as vscode from 'vscode';

suite('Notes Panel Extension', () => {
  test('Extension should be present', () => {
    const extension = vscode.extensions.getExtension('roid.notes-panel');
    assert.ok(extension, 'Extension not found in registry');
  });

  test('Extension should activate', async () => {
    const extension = vscode.extensions.getExtension('roid.notes-panel');
    assert.ok(extension, 'Extension not found');
    await extension.activate();
    assert.strictEqual(extension.isActive, true);
  });

  test('Notes view should be focusable', async () => {
    // This command is auto-generated by VS Code for registered views
    await vscode.commands.executeCommand('notesPanel.notesView.focus');
    // If it didn't throw, the view exists and is focusable
  });
});
